---
title: "Comparative Genomics Southern Flounder"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    highlight: kate
    theme: flatly
    toc: yes
  html_document:
    toc: yes
---

```{r load libraries, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

source("lib/libraries.R")
source("lib/ggplot.R")

```

# Finalize southern flounder linkage map

Import all merged consensus linkage groups.

```{r}

filenames <- list.files(path = "results", pattern = "*.consensus")

# import data
for (i in filenames){
  filepath <- file.path("results/", paste(i))
  assign(i, read.table(filepath, sep = "", header = TRUE))
  }


dflist_consensus <- lapply(ls(pattern = "*.consensus"), get)

map <- ldply(dflist_consensus, data.frame) %>%
    select(LOCUS, LG, POS)

write.table(map, "results/SFL.map", col.names = TRUE, quote = FALSE)

```

Number of markers per linkage group:

```{r}

temp <- count(map, LG)

temp

```

Length per linkage group:

```{r}

temp <- map %>%
    group_by(LG) %>%
    summarize(length = max(POS))

temp

```

Plot linkage map:

```{r}

# plot with ggplot
ggplot(map, aes(x = LG, y = POS)) +
  geom_path(aes(group = LG), size = 9, lineend = "round", col = "#325d81") +
  geom_path(aes(group = LG), size = 7.5, lineend = "round", col = "#edf3f8") +
  geom_rect(aes(xmin = LG-0.35, xmax = LG+0.35, 
                ymin = POS-0.025, ymax = POS+0.025),
            color = "#325d81", fill = "#325d81") +
  scale_x_continuous(breaks = c(1:24)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80)) +
  # scale_fill_manual(name="Marker Type",
  #                   breaks=c("est", "msat", "snp"),
  #                   labels=c("EST-SSR", "Microsatellite", "RAD Locus"),
  #                   values=c('#9e0142', '#a1d99b', '#2b8cbe') +
  labs(x = "\nLinkage Group", y = "Position (cM)\n") +
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.title.y = element_text(vjust = 1.5),
        axis.line.x = element_blank(),
        axis.line.y = element_line(color = "black", size = 1),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_line(color = "black", size = 1),
        axis.ticks.length = unit(0.2, "cm"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        
        legend.position = "bottom",
        
        panel.background = element_rect(fill = "white", color = NA), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        strip.background = element_rect(fill = "grey95", color = "black"), 
        strip.text.x = element_text(size = 16),
        strip.text.y = element_text(size = 16))

```

Linkage map Family A:

```{r}

FamA.map <- read.delim("data/LINKMAP/FamA.fullmap", 
                   stringsAsFactors = FALSE, sep = "", 
                   col.names = c("LG", "LOCUS", "POSITION"))

# plot with ggplot
ggplot(FamA.map, aes(x = LG, y = POSITION)) +
  geom_path(aes(group = LG), size = 9, lineend = "round", col = "#325d81") +
  geom_path(aes(group = LG), size = 7.5, lineend = "round", col = "#edf3f8") +
  geom_rect(aes(xmin = LG-0.35, xmax = LG+0.35, 
                ymin = POSITION-0.025, ymax = POSITION+0.025),
            color = "#325d81", fill = "#325d81") +
  scale_x_continuous(breaks = c(1:24)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80)) +
  # scale_fill_manual(name="Marker Type",
  #                   breaks=c("est", "msat", "snp"),
  #                   labels=c("EST-SSR", "Microsatellite", "RAD Locus"),
  #                   values=c('#9e0142', '#a1d99b', '#2b8cbe') +
  labs(x = "\nLinkage Group", y = "Position (cM)\n") +
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.title.y = element_text(vjust = 1.5),
        axis.line.x = element_blank(),
        axis.line.y = element_line(color = "black", size = 1),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_line(color = "black", size = 1),
        axis.ticks.length = unit(0.2, "cm"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        
        legend.position = "bottom",
        
        panel.background = element_rect(fill = "white", color = NA), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        strip.background = element_rect(fill = "grey95", color = "black"), 
        strip.text.x = element_text(size = 16),
        strip.text.y = element_text(size = 16))

```

Linkage Map Family B:

```{r}


FamB.map <- read.delim("data/LINKMAP/FamB.fullmap", 
                   header = TRUE, stringsAsFactors = FALSE, sep = "", 
                   col.names = c("LG", "LOCUS", "POSITION"))

ggplot(FamB.map, aes(x = LG, y = POSITION)) +
  geom_path(aes(group = LG), size = 9, lineend = "round", col = "#325d81") +
  geom_path(aes(group = LG), size = 7.5, lineend = "round", col = "#edf3f8") +
  geom_rect(aes(xmin = LG-0.35, xmax = LG+0.35, 
                ymin = POSITION-0.025, ymax = POSITION+0.025),
            color = "#325d81", fill = "#325d81") +
  scale_x_continuous(breaks = c(1:24)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80)) +
  # scale_fill_manual(name="Marker Type",
  #                   breaks=c("est", "msat", "snp"),
  #                   labels=c("EST-SSR", "Microsatellite", "RAD Locus"),
  #                   values=c('#9e0142', '#a1d99b', '#2b8cbe') +
  labs(x = "\nLinkage Group", y = "Position (cM)\n") +
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.title.y = element_text(vjust = 1.5),
        axis.line.x = element_blank(),
        axis.line.y = element_line(color = "black", size = 1),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_line(color = "black", size = 1),
        axis.ticks.length = unit(0.2, "cm"),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        
        legend.position = "bottom",
        
        panel.background = element_rect(fill = "white", color = NA), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        strip.background = element_rect(fill = "grey95", color = "black"), 
        strip.text.x = element_text(size = 16),
        strip.text.y = element_text(size = 16))

```

